//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.NEWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogA
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public Nullable<int> Operator { get; set; }
        public string Message { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string Operand { get; set; }
        public string IP { get; set; }
        public string MachineName { get; set; }
        public string Browser { get; set; }
        public string Location { get; set; }
        public string Exception { get; set; }
    }
}
