//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.NEWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public Nullable<int> CId { get; set; }
    }
}
